"""
HTML-структура отчёта.

Этот файл содержит только HTML-разметку.
Редактируй этот файл при изменении структуры страницы.
"""

HTML_BODY: str = """
    <!-- HEADER -->
    <header class="header">
      <div class="header-info">
        <h1>📊 Disk Space Analyzer Report</h1>
        <div class="header-meta">
          <div>Path: <strong id="scan-path">—</strong></div>
          <div>Generated: <strong id="report-date">—</strong></div>
        </div>
      </div>
    </header>

    <!-- DASHBOARD -->
    <section class="dashboard">
      <div class="card">
        <div class="card-label">📁 Total Files</div>
        <div class="card-value" id="stat-total-files">0</div>
      </div>
      <div class="card">
        <div class="card-label">💾 Total Size</div>
        <div class="card-value success" id="stat-total-size">0 B</div>
      </div>
      <div class="card">
        <div class="card-label">⏱️ Scan Duration</div>
        <div class="card-value" id="stat-duration">0.00s</div>
      </div>
      <div class="card">
        <div class="card-label">⚠️ Skipped Files</div>
        <div class="card-value warning" id="stat-skipped">0</div>
      </div>
      <div class="card">
        <div class="card-label">📈 Avg Uselessness</div>
        <div class="card-value" id="stat-avg-useless">0 MB·days</div>
      </div>
    </section>

    <!-- TOP FILES + CHARTS -->
    <section class="charts-row">
      <div class="chart-container">
        <h3 class="chart-title">🏆 Top 10 Useless Files</h3>
        <ul class="top-files-list" id="top-files-list"></ul>
      </div>
      <div class="chart-container">
        <h3 class="chart-title">📊 Files by Extension</h3>
        <div class="chart-canvas-wrapper">
          <canvas id="ext-chart"></canvas>
        </div>
      </div>
    </section>

    <!-- CONTROLS -->
    <section class="controls">
      <div class="search-box">
        <input type="text" id="search-input" placeholder="🔍 Search files..." aria-label="Search files">
      </div>
      <div class="controls-right">
        <select class="pagination-select" id="per-page-select" aria-label="Items per page">
          <option value="25">25 per page</option>
          <option value="50" selected>50 per page</option>
          <option value="100">100 per page</option>
          <option value="250">250 per page</option>
          <option value="500">500 (slow)</option>
        </select>
        <button class="btn btn-secondary" id="export-csv-btn" title="Export to CSV">
          📥 Export CSV
        </button>
      </div>
    </section>

    <!-- TABLE -->
    <section class="table-container">
      <div class="table-wrapper">
        <table id="files-table">
          <colgroup>
            <col style="width: 5%">
            <col style="width: 30%">
            <col style="width: 15%">
            <col style="width: 6%">
            <col style="width: 10%">
            <col style="width: 7%">
            <col style="width: 12%">
            <col style="width: 15%">
          </colgroup>
          <thead>
            <tr>
              <th data-sort="uselessness_level">Level<span class="sort-icon">↕</span></th>
              <th data-sort="path">Path<span class="sort-icon">↕</span></th>
              <th data-sort="name">Name<span class="sort-icon">↕</span></th>
              <th data-sort="extension">Ext<span class="sort-icon">↕</span></th>
              <th data-sort="size_human">Size<span class="sort-icon">↕</span></th>
              <th data-sort="idle_days">Idle Days<span class="sort-icon">↕</span></th>
              <th data-sort="uselessness_index">Uselessness<span class="sort-icon">↕</span></th>
              <th data-sort="uselessness_human">Uselessness (human)<span class="sort-icon">↕</span></th>
            </tr>
          </thead>
          <tbody id="table-body">
            <!-- Rows will be inserted here -->
          </tbody>
        </table>
      </div>
      <div class="pagination" id="pagination">
        <!-- Pagination controls will be inserted here -->
      </div>
    </section>

    <!-- FOOTER -->
    <footer class="footer">
      <p>Generated by Disk Space Analyzer v<span id="app-version">{version}</span></p>
      <p>Report generated at <span id="footer-date">—</span></p>
    </footer>
"""
